name: {INIT_PROJECT_SLUG}-local

x-api-environment: &api-environment
  ASPNETCORE_ENVIRONMENT: Development
  ConnectionStrings__Database: Host=db;Port=5432;Database={INIT_PROJECT_SLUG};Username=admin;Password=pwd
  Caching__Redis__Enabled: true
  Caching__Redis__ConnectionString: redis:6379
  Caching__Redis__Password: redis-dev-password
  Caching__Redis__UseSsl: false
  Caching__Redis__DefaultDatabase: 0
  Caching__Redis__InstanceName: "{INIT_PROJECT_SLUG}:"
  Caching__Redis__AbortOnConnectFail: false
  Authentication__Jwt__ExpiresInMinutes: 100
  Authentication__Jwt__RefreshTokenExpiresInDays: 7
  Serilog__WriteTo__0__Name: Seq
  Serilog__WriteTo__0__Args__serverUrl: http://seq:80

x-db-environment: &db-environment
  POSTGRES_DB: {INIT_PROJECT_SLUG}
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: pwd

x-frontend-environment: &frontend-environment
  API_URL: http://api:8080

x-common-settings: &common-settings
  restart: unless-stopped
  networks:
    - application_network

services:
  api:
    build:
      context: ./src/backend
      dockerfile: MyProject.WebApi/Dockerfile
    container_name: {INIT_PROJECT_SLUG}-local-api
    environment: *api-environment
    <<: *common-settings
    ports:
      - "{INIT_API_PORT}:8080"
    depends_on:
      - db
      - redis
      - seq

  seq:
    image: datalust/seq:latest
    container_name: {INIT_PROJECT_SLUG}-local-seq
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_NOAUTHENTICATION=true
    ports:
      - "{INIT_SEQ_PORT}:80"
    <<: *common-settings
    volumes:
      - seq_data:/data

  redis:
    image: redis:7-alpine
    container_name: {INIT_PROJECT_SLUG}-local-redis
    <<: *common-settings
    ports:
      - "{INIT_REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass redis-dev-password

  db:
    image: postgres:15-alpine
    container_name: {INIT_PROJECT_SLUG}-local-db
    environment: *db-environment
    <<: *common-settings
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "{INIT_DB_PORT}:5432"

  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile.local
    container_name: {INIT_PROJECT_SLUG}-local-frontend
    environment: *frontend-environment
    volumes:
      - ./src/frontend:/app
      - frontend_node_modules:/app/node_modules
    ports:
      - "{INIT_FRONTEND_PORT}:5173"
    depends_on:
      - api
    <<: *common-settings

volumes:
  db_data:
    name: {INIT_PROJECT_SLUG}-local-db-data
  redis_data:
    name: {INIT_PROJECT_SLUG}-local-redis-data
  seq_data:
    name: {INIT_PROJECT_SLUG}-local-seq-data
  frontend_node_modules:
    name: {INIT_PROJECT_SLUG}-local-frontend-node-modules

networks:
  application_network:
    name: {INIT_PROJECT_SLUG}-local-network
    driver: bridge
